### ISSUE TITLE
diazo theme blocked

### ISSUE THREAD

**Issue by ginetsl** [collective/experimental.noacquisition#1]
Hello,

I was testing this product on my plone site to block acquisition when requesting content on any of the subsites inside it. It does its work, but it also blocks access to the diazo theme and its resources.

My current setup:
Plone = 5.0.6
plone.app.theming = 1.3.0

One plone site at the root, and subfolders with navigation root behavior applied. The root site and all the subsites use the same diazo theme (installed on the root site).
The plone site and each subsite have their own domain name, so they are accessed like this:

parentsite.com for the parent site
subsiteX.com for each parent/subfolder with navigation root behavior enabled

I currently have dryrun=True, and the warnings shown on the logs are of the form:

WARNING experimental.noacquisition traverse without explicit acquisition object=<Folder at /parent/subsite> name='parent' subobject=<PloneSite at /parent used for /parent/subsite> url='http://subsite.com/parent/++theme++mytheme/images/favicon.ico' referer=''

If I set dryrun to False I get totally unthemed pages for the parent and any of the subsites.

My apologies if this is not clear enough or if I am missing important details. I'd be more than happy to provide more information/explanations.

Thank you,

Ginet

**Comment by mamico** [comment]
@ginetsl 

As a workaround you could try to replace apache rule with **something** like

```
RewriteRule ^/+parent(/\+\+theme\+\+.*) $1
RewriteRule ^(/.*)?$ http://127.0.0.1:XXXXX/VirtualHostBase/http/subsite.com:80/parent/subsite/VirtualHostRoot$1 [L,P]
```

or

`RewriteRule ^(/+parent)?(/.*)?$ http://127.0.0.1:XXXXX/VirtualHostBase/http/subsite.com:80/parent/subsite/VirtualHostRoot$2 [L,P]`

but IMO the problem is not related to experimental.noacquisition: the url http://subsite.com/parent/++theme++mytheme/images/favicon.ico is wrong and correctly catched. (sorry)
